CREATE DATABASE IF NOT EXISTS play_test CHARACTER SET utf8 COLLATE utf8_general_ci;

USE play_test;
CREATE TABLE IF NOT EXISTS students (
  id INT(3) UNSIGNED NOT NULL AUTO_INCREMENT,
  firstName VARCHAR(100) NOT NULL,
  lastName VARCHAR(100) NOT NULL,
  age INT(3) NOT NULL ,
  PRIMARY KEY (id)
);
